name: linter-run
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
            - name: chekout repo
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - uses: abatilo/actions-poetry@v2.0.0
              run: make lint
