name: linter-run
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
            - name: chekout repo
              uses: actions/checkout@v2
            - name: run linter
              run: make lint
