name: linter-run
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
            - name: chekout repo
              uses: actions/checkout@v2
            - name: setup python 
              uses: actions/setup-python@v2
            - name: run python dependencies 
              run: python -m pip install --upgrade pip requests
            - name: install poetry
              uses: abatilo/actions-poetry@v2.0.0
              run: make lint
